import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 0,
    name: "Toronto #0",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 1,
    name: "Toronto #1",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 2,
    name: "Toronto #2",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 3,
    name: "Toronto #3",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 4,
    name: "Toronto #4",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 5,
    name: "Toronto #5",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 6,
    name: "Toronto #6",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 7,
    name: "Winnipeg #0",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 8,
    name: "Winnipeg #1",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 9,
    name: "Winnipeg #2",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 10,
    name: "Winnipeg #3",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 11,
    name: "Winnipeg #4",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 12,
    name: "Winnipeg #5",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 13,
    name: "Winnipeg #6",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 14,
    name: "Winnipeg #7",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/7.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 15,
    name: "Winnipeg #8",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/8.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 16,
    name: "Vancouver #0",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 17,
    name: "Vancouver #1",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 18,
    name: "Vancouver #2",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 19,
    name: "Vancouver #3",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 20,
    name: "Vancouver #4",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 21,
    name: "Vancouver #5",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 22,
    name: "Vancouver #6",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 23,
    name: "Vancouver #7",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/7.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
];
