import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 24,
    name: "Montreal #0",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 25,
    name: "Montreal #1",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 26,
    name: "Montreal #2",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 27,
    name: "Montreal #3",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 28,
    name: "Montreal #4",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 29,
    name: "Montreal #5",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 30,
    name: "Montreal #6",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 31,
    name: "Montreal #7",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/7.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 32,
    name: "Montreal #8",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/8.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 33,
    name: "Baltimore #0",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/0.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 34,
    name: "Baltimore #1",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/1.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 35,
    name: "Baltimore #2",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/2.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 36,
    name: "Baltimore #3",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/3.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 37,
    name: "Baltimore #4",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/4.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 38,
    name: "Baltimore #5",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/5.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 39,
    name: "Baltimore #6",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/6.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 40,
    name: "Baltimore #7",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/7.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 41,
    name: "Baltimore #8",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/8.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 42,
    name: "Syracuse #0",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/0.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 43,
    name: "Syracuse #1",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/1.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 44,
    name: "Syracuse #2",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/2.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 45,
    name: "Syracuse #3",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/3.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 46,
    name: "Syracuse #4",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/4.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 47,
    name: "Syracuse #5",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/5.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
];
