import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 48,
    name: "Syracuse #6",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/6.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 49,
    name: "Syracuse #7",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/7.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 50,
    name: "Syracuse #8",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/8.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 51,
    name: "New York #0",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/0.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 52,
    name: "New York #1",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/1.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 53,
    name: "New York #2",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/2.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 54,
    name: "New York #3",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/3.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 55,
    name: "New York #4",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/4.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 56,
    name: "New York #5",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/5.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 57,
    name: "New York #6",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/6.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 58,
    name: "New York #7",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/7.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 59,
    name: "New York #8",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/8.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 60,
    name: "Paris #0",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/0.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 61,
    name: "Paris #1",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/1.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 62,
    name: "Paris #2",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/2.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 63,
    name: "Paris #3",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/3.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 64,
    name: "Paris #4",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/4.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 65,
    name: "Paris #5",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/5.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 66,
    name: "Paris #6",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/6.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 67,
    name: "Paris #7",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/7.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 68,
    name: "Paris #8",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/8.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 69,
    name: "Amsterdam #0",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/0.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 70,
    name: "Amsterdam #1",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/1.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 71,
    name: "Amsterdam #2",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/2.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
];
