import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 72,
    name: "Amsterdam #3",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/3.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 73,
    name: "Amsterdam #4",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/4.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 74,
    name: "Amsterdam #5",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/5.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 75,
    name: "Amsterdam #6",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/6.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 76,
    name: "Amsterdam #7",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/7.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 77,
    name: "Amsterdam #8",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/8.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 78,
    name: "Berlin #0",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/0.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 79,
    name: "Berlin #1",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/1.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 80,
    name: "Berlin #2",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/2.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 81,
    name: "Berlin #3",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/3.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 82,
    name: "Berlin #4",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/4.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 83,
    name: "Berlin #5",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/5.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 84,
    name: "Berlin #6",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/6.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 85,
    name: "Berlin #7",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/7.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 86,
    name: "Berlin #8",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/8.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 87,
    name: "Frankfurt #0",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/0.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 88,
    name: "Frankfurt #1",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/1.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 89,
    name: "Frankfurt #2",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/2.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 90,
    name: "Frankfurt #3",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/3.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 91,
    name: "Frankfurt #4",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/4.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 92,
    name: "Frankfurt #5",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/5.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 93,
    name: "Frankfurt #6",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/6.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 94,
    name: "Frankfurt #7",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/7.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 95,
    name: "Frankfurt #8",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/8.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
];
