import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 96,
    name: "Munich #0",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/0.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 97,
    name: "Munich #1",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/1.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 98,
    name: "Munich #2",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/2.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 99,
    name: "Munich #3",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/3.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 100,
    name: "Munich #4",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/4.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 101,
    name: "Munich #5",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/5.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 102,
    name: "Munich #6",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/6.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 103,
    name: "Munich #7",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/7.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 104,
    name: "Munich #8",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/8.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 105,
    name: "Vienna #0",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/0.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 106,
    name: "Vienna #1",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/1.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 107,
    name: "Vienna #2",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/2.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 108,
    name: "Vienna #3",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/3.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 109,
    name: "Vienna #4",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/4.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 110,
    name: "Vienna #5",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/5.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 111,
    name: "Vienna #6",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/6.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 112,
    name: "Vienna #7",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/7.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 113,
    name: "Vienna #8",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/8.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 114,
    name: "Vung Tau #0",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/0.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 115,
    name: "Vung Tau #1",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/1.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 116,
    name: "Vung Tau #2",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/2.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 117,
    name: "Vung Tau #3",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/3.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 118,
    name: "Vung Tau #4",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/4.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 119,
    name: "Vung Tau #5",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/5.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
];
