import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 120,
    name: "Vung Tau #6",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/6.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 121,
    name: "Vung Tau #7",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/7.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 122,
    name: "Vung Tau #8",
    description: "",
    url: "ipfs://bafybeiep2574gf6z3qbenp5twmcuzzmk5vp3a77rhw7wpjufy7yfxzcwiu/8.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Vung Tau",
    continent: "Asia",
  },
  {
    id: 123,
    name: "Da Lat #0",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/0.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 124,
    name: "Da Lat #1",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/1.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 125,
    name: "Da Lat #2",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/2.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 126,
    name: "Da Lat #3",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/3.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 127,
    name: "Da Lat #4",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/4.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 128,
    name: "Da Lat #5",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/5.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 129,
    name: "Da Lat #6",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/6.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 130,
    name: "Da Lat #7",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/7.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 131,
    name: "Da Lat #8",
    description: "",
    url: "ipfs://bafybeidchbpp2sy67lg7oepocqkd3gihnssdz2trg4qpvfqg4geossar5u/8.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Da Lat",
    continent: "Asia",
  },
  {
    id: 132,
    name: "Ha Noi #0",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/0.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 133,
    name: "Ha Noi #1",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/1.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 134,
    name: "Ha Noi #2",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/2.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 135,
    name: "Ha Noi #3",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/3.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 136,
    name: "Ha Noi #4",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/4.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 137,
    name: "Ha Noi #5",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/5.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 138,
    name: "Ha Noi #6",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/6.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 139,
    name: "Ha Noi #7",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/7.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 140,
    name: "Ha Noi #8",
    description: "",
    url: "ipfs://bafybeihthtvfiix2wg46brtos6njemx6igms26cfgwwmgo4iamyrehsgna/8.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Ha Noi",
    continent: "Asia",
  },
  {
    id: 141,
    name: "Thai Binh #0",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/0.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 142,
    name: "Thai Binh #1",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/1.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 143,
    name: "Thai Binh #2",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/2.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
];
