import { CityBadgeNft } from "./nfts";

export const data: CityBadgeNft[] = [
  {
    id: 144,
    name: "Thai Binh #3",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/3.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 145,
    name: "Thai Binh #4",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/4.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 146,
    name: "Thai Binh #5",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/5.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 147,
    name: "Thai Binh #6",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/6.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 148,
    name: "Thai Binh #7",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/7.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 149,
    name: "Thai Binh #8",
    description: "",
    url: "ipfs://bafybeig3nf4q6jlchogykyesrcvpo3pst6dh46ii3lykpozzuxrdrnpruu/8.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Thai Binh",
    continent: "Asia",
  },
  {
    id: 150,
    name: "Sai Gon #0",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/0.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 151,
    name: "Sai Gon #1",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/1.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 152,
    name: "Sai Gon #2",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/2.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 153,
    name: "Sai Gon #3",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/3.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 154,
    name: "Sai Gon #4",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/4.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 155,
    name: "Sai Gon #5",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/5.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 156,
    name: "Sai Gon #6",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/6.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 157,
    name: "Sai Gon #7",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/7.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 158,
    name: "Sai Gon #8",
    description: "",
    url: "ipfs://bafybeicis4wajbms5ch7cz6v6nckabzxkp35qowghxnxzawe57ov24lgbe/8.png",
    price: 0.04,
    minted: false,
    country: "Vietnam",
    city: "Sai Gon",
    continent: "Asia",
  },
  {
    id: 159,
    name: "Kuala Lumpur #0",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/0.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 160,
    name: "Kuala Lumpur #1",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/1.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 161,
    name: "Kuala Lumpur #2",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/2.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 162,
    name: "Kuala Lumpur #3",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/3.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 163,
    name: "Kuala Lumpur #4",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/4.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 164,
    name: "Kuala Lumpur #5",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/5.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 165,
    name: "Kuala Lumpur #6",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/6.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 166,
    name: "Kuala Lumpur #7",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/7.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 167,
    name: "Kuala Lumpur #8",
    description: "",
    url: "ipfs://bafybeigvr7pde5maq2sjckv7hzz4bsuj2btxdf45g3igcyk562kupni4yu/8.png",
    price: 0.04,
    minted: false,
    country: "Malaysia",
    city: "Kuala Lumpur",
    continent: "Asia",
  },
];
