import { Continent } from "./continents";
import { Country } from "./countries";

export type CityBadgeNft = {
  id: number;
  name: string;
  description: string;
  url: string;
  price: number;
  minted: boolean;
  country: Country;
  city: string;
  continent: Continent;
};
export const NFTs: CityBadgeNft[] = [
  {
    id: 0,
    name: "Toronto #0",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 1,
    name: "Toronto #1",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 2,
    name: "Toronto #2",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 3,
    name: "Toronto #3",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 4,
    name: "Toronto #4",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 5,
    name: "Toronto #5",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 6,
    name: "Toronto #6",
    description: "",
    url: "ipfs://QmaUN81MtipKDLzS1NGBz1h3RuHBoDTJar8wMZVHrWv2sJ/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Toronto",
    continent: "North America",
  },
  {
    id: 7,
    name: "Winnipeg #0",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 8,
    name: "Winnipeg #1",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 9,
    name: "Winnipeg #2",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 10,
    name: "Winnipeg #3",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 11,
    name: "Winnipeg #4",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 12,
    name: "Winnipeg #5",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 13,
    name: "Winnipeg #6",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 14,
    name: "Winnipeg #7",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/7.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 15,
    name: "Winnipeg #8",
    description: "",
    url: "ipfs://QmWaguwqg8EAhQWrftkfT4u1AHsRHtS2MJVf6cUvb6SpJZ/8.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Winnipeg",
    continent: "North America",
  },
  {
    id: 16,
    name: "Vancouver #0",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 17,
    name: "Vancouver #1",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 18,
    name: "Vancouver #2",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 19,
    name: "Vancouver #3",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 20,
    name: "Vancouver #4",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 21,
    name: "Vancouver #5",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 22,
    name: "Vancouver #6",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 23,
    name: "Vancouver #7",
    description: "",
    url: "ipfs://QmQxYjNdUPGXBC1sX1c8WWuwmq7S6FLR2xJKMbBYSzRGJo/7.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Vancouver",
    continent: "North America",
  },
  {
    id: 24,
    name: "Montreal #0",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/0.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 25,
    name: "Montreal #1",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/1.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 26,
    name: "Montreal #2",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/2.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 27,
    name: "Montreal #3",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/3.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 28,
    name: "Montreal #4",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/4.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 29,
    name: "Montreal #5",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/5.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 30,
    name: "Montreal #6",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/6.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 31,
    name: "Montreal #7",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/7.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 32,
    name: "Montreal #8",
    description: "",
    url: "ipfs://QmUu8NxKsNBLm1dTrjhynKgByceAnXwPwSSyh7yL86Rmvg/8.png",
    price: 0.04,
    minted: false,
    country: "Canada",
    city: "Montreal",
    continent: "North America",
  },
  {
    id: 33,
    name: "Baltimore #0",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/0.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 34,
    name: "Baltimore #1",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/1.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 35,
    name: "Baltimore #2",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/2.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 36,
    name: "Baltimore #3",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/3.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 37,
    name: "Baltimore #4",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/4.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 38,
    name: "Baltimore #5",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/5.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 39,
    name: "Baltimore #6",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/6.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 40,
    name: "Baltimore #7",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/7.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 41,
    name: "Baltimore #8",
    description: "",
    url: "ipfs://QmRKq9h76awH1RyzbZYJMgYZNTB1Rqt8HWSAVmW2LcPcFQ/8.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Baltimore",
    continent: "North America",
  },
  {
    id: 42,
    name: "Syracuse #0",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/0.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 43,
    name: "Syracuse #1",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/1.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 44,
    name: "Syracuse #2",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/2.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 45,
    name: "Syracuse #3",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/3.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 46,
    name: "Syracuse #4",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/4.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 47,
    name: "Syracuse #5",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/5.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 48,
    name: "Syracuse #6",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/6.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 49,
    name: "Syracuse #7",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/7.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 50,
    name: "Syracuse #8",
    description: "",
    url: "ipfs://QmRZ8dBRKwXWraMisqHWd5xkQJZA5Dnh3BD8UuTnjKvcJL/8.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "Syracuse",
    continent: "North America",
  },
  {
    id: 51,
    name: "New York #0",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/0.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 52,
    name: "New York #1",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/1.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 53,
    name: "New York #2",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/2.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 54,
    name: "New York #3",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/3.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 55,
    name: "New York #4",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/4.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 56,
    name: "New York #5",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/5.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 57,
    name: "New York #6",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/6.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 58,
    name: "New York #7",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/7.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 59,
    name: "New York #8",
    description: "",
    url: "ipfs://QmPebEFmUhq4xobop8uo6Nx2f7pm9Rd4Pwa17Lp4FSi1ud/8.png",
    price: 0.04,
    minted: false,
    country: "USA",
    city: "New York",
    continent: "North America",
  },
  {
    id: 60,
    name: "Paris #0",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/0.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 61,
    name: "Paris #1",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/1.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 62,
    name: "Paris #2",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/2.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 63,
    name: "Paris #3",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/3.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 64,
    name: "Paris #4",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/4.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 65,
    name: "Paris #5",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/5.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 66,
    name: "Paris #6",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/6.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 67,
    name: "Paris #7",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/7.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 68,
    name: "Paris #8",
    description: "",
    url: "ipfs://QmYKGgypBmaDvYw3qHpZCFhF7b9RsBktgNxgvv6ZpRFJmw/8.png",
    price: 0.04,
    minted: false,
    country: "France",
    city: "Paris",
    continent: "Europe",
  },
  {
    id: 69,
    name: "Amsterdam #0",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/0.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 70,
    name: "Amsterdam #1",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/1.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 71,
    name: "Amsterdam #2",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/2.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 72,
    name: "Amsterdam #3",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/3.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 73,
    name: "Amsterdam #4",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/4.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 74,
    name: "Amsterdam #5",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/5.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 75,
    name: "Amsterdam #6",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/6.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 76,
    name: "Amsterdam #7",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/7.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 77,
    name: "Amsterdam #8",
    description: "",
    url: "ipfs://Qmck3jpzbD2WibH5GLCCZrZyUVW6VUk7KRxRRBxsEPaLVt/8.png",
    price: 0.04,
    minted: false,
    country: "Netherland",
    city: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 78,
    name: "Berlin #0",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/0.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 79,
    name: "Berlin #1",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/1.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 80,
    name: "Berlin #2",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/2.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 81,
    name: "Berlin #3",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/3.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 82,
    name: "Berlin #4",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/4.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 83,
    name: "Berlin #5",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/5.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 84,
    name: "Berlin #6",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/6.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 85,
    name: "Berlin #7",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/7.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 86,
    name: "Berlin #8",
    description: "",
    url: "ipfs://QmbeYSrhRzkZ1h5PbyCPFQCV6cmpHyUkFuHgXntGkiAd5P/8.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Berlin",
    continent: "Europe",
  },
  {
    id: 87,
    name: "Frankfurt #0",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/0.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 88,
    name: "Frankfurt #1",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/1.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 89,
    name: "Frankfurt #2",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/2.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 90,
    name: "Frankfurt #3",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/3.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 91,
    name: "Frankfurt #4",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/4.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 92,
    name: "Frankfurt #5",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/5.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 93,
    name: "Frankfurt #6",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/6.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 94,
    name: "Frankfurt #7",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/7.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 95,
    name: "Frankfurt #8",
    description: "",
    url: "ipfs://QmaRdjBuEFQuGMJKxshd4aNiM97jFoieWzRC3YVxAR61Fu/8.jpg",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Frankfurt",
    continent: "Europe",
  },
  {
    id: 96,
    name: "Munich #0",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/0.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 97,
    name: "Munich #1",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/1.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 98,
    name: "Munich #2",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/2.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 99,
    name: "Munich #3",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/3.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 100,
    name: "Munich #4",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/4.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 101,
    name: "Munich #5",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/5.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 102,
    name: "Munich #6",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/6.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 103,
    name: "Munich #7",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/7.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 104,
    name: "Munich #8",
    description: "",
    url: "ipfs://QmXdyqhWSHsSy6bchP1cexV64t5zrmfP6JCXGVhiFPaWVM/8.png",
    price: 0.04,
    minted: false,
    country: "Germany",
    city: "Munich",
    continent: "Europe",
  },
  {
    id: 105,
    name: "Vienna #0",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/0.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 106,
    name: "Vienna #1",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/1.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 107,
    name: "Vienna #2",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/2.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 108,
    name: "Vienna #3",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/3.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 109,
    name: "Vienna #4",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/4.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 110,
    name: "Vienna #5",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/5.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 111,
    name: "Vienna #6",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/6.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 112,
    name: "Vienna #7",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/7.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
  {
    id: 113,
    name: "Vienna #8",
    description: "",
    url: "ipfs://QmfRJaXDGCdnFrZHBoEue2CWs6puz2nZ4qgJxbKpyEVbRJ/8.png",
    price: 0.04,
    minted: false,
    country: "Austria",
    city: "Vienna",
    continent: "Europe",
  },
];
