import Container from "../components/Container";
import {
  MARKETPLACE_CONTRACT_ADDRESS,
  MINT_CONTRACT_ADDRESS,
} from "../utils/contractAddress";

const AboutPage = () => {
  return (
    <Container>
      <p style={{ maxWidth: "650px", marginLeft: "auto", marginRight: "auto" }}>
        City Badges is an image collection of cities around the world. The NFTs
        are generated by DALL-E and live on the Avalanche blockchain.
        <br />
        <br />
        Built with Next JS and Thirdweb SDK
        <br />
        <hr />
        <span>
          <b>Mint Contract address:</b> {MINT_CONTRACT_ADDRESS}
        </span>
        <br />
        <a
          href={`https://snowtrace.io/address/${MINT_CONTRACT_ADDRESS}`}
          target="_blank"
          rel="noopener noreferrer"
        >
          Link: https://snowtrace.io/address/{MINT_CONTRACT_ADDRESS}
        </a>
        <br /><br/>
        <span>
          <b>Marketplace Contract address:</b> {MARKETPLACE_CONTRACT_ADDRESS}
        </span>
        <br />
        <a
          href={`https://snowtrace.io/address/${MARKETPLACE_CONTRACT_ADDRESS}`}
          target="_blank"
          rel="noopener noreferrer"
        >
          Link: https://snowtrace.io/address/{MARKETPLACE_CONTRACT_ADDRESS}
        </a>
      </p>
    </Container>
  );
};

export default AboutPage;
