import Container from "../components/Container";
import { CONTRACT_ADDRESS } from "../utils/contractAddress";

const AboutPage = () => {
  return (
    <Container>
      <p style={{ maxWidth: "650px", marginLeft: "auto", marginRight: "auto" }}>
        City Badges is an image collection of cities around the world. The NFTs
        are generated by DALL-E and live on the Avalanche blockchain.
        <br />
        <br />
        Built with Next JS and Thirdweb SDk
        <br />
        <span>Contract address: {CONTRACT_ADDRESS}</span><br/>
        <a
          href={`https://snowtrace.io/address/${CONTRACT_ADDRESS}`}
          target="_blank"
          rel="noopener noreferrer"
        >
          Link: https://snowtrace.io/address/{CONTRACT_ADDRESS}
        </a>
      </p>
    </Container>
  );
};

export default AboutPage;
