import type { NextPage } from "next";
import Link from "next/link";
import Container from "../components/Container";
import styles from "../styles/Home.module.css";
import { CONTRACTS, CURRENT_CHAIN } from "../utils/contractAddress";

const Home: NextPage = () => {
  return (
    <Container>
      <p style={{ maxWidth: "650px", marginLeft: "auto", marginRight: "auto" }}>
        City Badges is an image collection of cities around the world. The NFTs
        are generated by DALL-E and live on the Avalanche blockchain.<br/><br/>
        <Link href="/mint">
          <a style={{fontSize: '20px', padding: '10px', border: '1px solid #333', display: 'block', width: 'fit-content'}}>Mint Now!</a>
        </Link>
        <br />
        <br />
        Built with Next JS and Thirdweb SDK
        <br />
      </p>
      <hr />
      <p style={{ maxWidth: "650px", marginLeft: "auto", marginRight: "auto" }}>
        <span>
          <b>Mint Contract address:</b> {CONTRACTS.MINT[CURRENT_CHAIN]}
        </span>
        <br />
        <a
          href={`https://snowtrace.io/address/${CONTRACTS.MINT[CURRENT_CHAIN]}`}
          target="_blank"
          rel="noopener noreferrer"
        >
          Link: https://snowtrace.io/address/{CONTRACTS.MINT[CURRENT_CHAIN]}
        </a>
        <br />
        <br />
        <span>
          <b>Marketplace Contract address:</b> {CONTRACTS.MARKETPLACE[CURRENT_CHAIN]}
        </span>
        <br />
        <a
          href={`https://snowtrace.io/address/${CONTRACTS.MARKETPLACE[CURRENT_CHAIN]}`}
          target="_blank"
          rel="noopener noreferrer"
        >
          Link: https://snowtrace.io/address/{CONTRACTS.MARKETPLACE[CURRENT_CHAIN]}
        </a>
      </p>
    </Container>
  );
};

export default Home;
